// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataClassProtoBufSerDeProxy.proto

package dataObject;

public final class DataClassProtoBufProxy {
  private DataClassProtoBufProxy() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DataClassOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dataObject.DataClass)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * use of "required" is discouraged - makes all future versions brittle!
     * </pre>
     *
     * <code>string data = 1;</code>
     */
    java.lang.String getData();
    /**
     * <pre>
     * use of "required" is discouraged - makes all future versions brittle!
     * </pre>
     *
     * <code>string data = 1;</code>
     */
    com.google.protobuf.ByteString
        getDataBytes();

    /**
     * <pre>
     *in proto3 field are optiona by default
     * </pre>
     *
     * <code>string hexVersion = 20;</code>
     */
    java.lang.String getHexVersion();
    /**
     * <pre>
     *in proto3 field are optiona by default
     * </pre>
     *
     * <code>string hexVersion = 20;</code>
     */
    com.google.protobuf.ByteString
        getHexVersionBytes();
  }
  /**
   * <pre>
   * [START messages]
   * </pre>
   *
   * Protobuf type {@code dataObject.DataClass}
   */
  public  static final class DataClass extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dataObject.DataClass)
      DataClassOrBuilder {
    // Use DataClass.newBuilder() to construct.
    private DataClass(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DataClass() {
      data_ = "";
      hexVersion_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private DataClass(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              data_ = s;
              break;
            }
            case 162: {
              java.lang.String s = input.readStringRequireUtf8();

              hexVersion_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dataObject.DataClassProtoBufProxy.internal_static_dataObject_DataClass_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dataObject.DataClassProtoBufProxy.internal_static_dataObject_DataClass_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dataObject.DataClassProtoBufProxy.DataClass.class, dataObject.DataClassProtoBufProxy.DataClass.Builder.class);
    }

    public static final int DATA_FIELD_NUMBER = 1;
    private volatile java.lang.Object data_;
    /**
     * <pre>
     * use of "required" is discouraged - makes all future versions brittle!
     * </pre>
     *
     * <code>string data = 1;</code>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        data_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * use of "required" is discouraged - makes all future versions brittle!
     * </pre>
     *
     * <code>string data = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HEXVERSION_FIELD_NUMBER = 20;
    private volatile java.lang.Object hexVersion_;
    /**
     * <pre>
     *in proto3 field are optiona by default
     * </pre>
     *
     * <code>string hexVersion = 20;</code>
     */
    public java.lang.String getHexVersion() {
      java.lang.Object ref = hexVersion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hexVersion_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *in proto3 field are optiona by default
     * </pre>
     *
     * <code>string hexVersion = 20;</code>
     */
    public com.google.protobuf.ByteString
        getHexVersionBytes() {
      java.lang.Object ref = hexVersion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hexVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, data_);
      }
      if (!getHexVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 20, hexVersion_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, data_);
      }
      if (!getHexVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(20, hexVersion_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dataObject.DataClassProtoBufProxy.DataClass)) {
        return super.equals(obj);
      }
      dataObject.DataClassProtoBufProxy.DataClass other = (dataObject.DataClassProtoBufProxy.DataClass) obj;

      boolean result = true;
      result = result && getData()
          .equals(other.getData());
      result = result && getHexVersion()
          .equals(other.getHexVersion());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + HEXVERSION_FIELD_NUMBER;
      hash = (53 * hash) + getHexVersion().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dataObject.DataClassProtoBufProxy.DataClass parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dataObject.DataClassProtoBufProxy.DataClass parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dataObject.DataClassProtoBufProxy.DataClass parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dataObject.DataClassProtoBufProxy.DataClass parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dataObject.DataClassProtoBufProxy.DataClass parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dataObject.DataClassProtoBufProxy.DataClass parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dataObject.DataClassProtoBufProxy.DataClass parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dataObject.DataClassProtoBufProxy.DataClass parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dataObject.DataClassProtoBufProxy.DataClass parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dataObject.DataClassProtoBufProxy.DataClass parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dataObject.DataClassProtoBufProxy.DataClass prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * [START messages]
     * </pre>
     *
     * Protobuf type {@code dataObject.DataClass}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dataObject.DataClass)
        dataObject.DataClassProtoBufProxy.DataClassOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dataObject.DataClassProtoBufProxy.internal_static_dataObject_DataClass_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dataObject.DataClassProtoBufProxy.internal_static_dataObject_DataClass_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dataObject.DataClassProtoBufProxy.DataClass.class, dataObject.DataClassProtoBufProxy.DataClass.Builder.class);
      }

      // Construct using dataObject.DataClassProtoBufProxy.DataClass.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        data_ = "";

        hexVersion_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dataObject.DataClassProtoBufProxy.internal_static_dataObject_DataClass_descriptor;
      }

      public dataObject.DataClassProtoBufProxy.DataClass getDefaultInstanceForType() {
        return dataObject.DataClassProtoBufProxy.DataClass.getDefaultInstance();
      }

      public dataObject.DataClassProtoBufProxy.DataClass build() {
        dataObject.DataClassProtoBufProxy.DataClass result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public dataObject.DataClassProtoBufProxy.DataClass buildPartial() {
        dataObject.DataClassProtoBufProxy.DataClass result = new dataObject.DataClassProtoBufProxy.DataClass(this);
        result.data_ = data_;
        result.hexVersion_ = hexVersion_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dataObject.DataClassProtoBufProxy.DataClass) {
          return mergeFrom((dataObject.DataClassProtoBufProxy.DataClass)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dataObject.DataClassProtoBufProxy.DataClass other) {
        if (other == dataObject.DataClassProtoBufProxy.DataClass.getDefaultInstance()) return this;
        if (!other.getData().isEmpty()) {
          data_ = other.data_;
          onChanged();
        }
        if (!other.getHexVersion().isEmpty()) {
          hexVersion_ = other.hexVersion_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dataObject.DataClassProtoBufProxy.DataClass parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dataObject.DataClassProtoBufProxy.DataClass) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object data_ = "";
      /**
       * <pre>
       * use of "required" is discouraged - makes all future versions brittle!
       * </pre>
       *
       * <code>string data = 1;</code>
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * use of "required" is discouraged - makes all future versions brittle!
       * </pre>
       *
       * <code>string data = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * use of "required" is discouraged - makes all future versions brittle!
       * </pre>
       *
       * <code>string data = 1;</code>
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * use of "required" is discouraged - makes all future versions brittle!
       * </pre>
       *
       * <code>string data = 1;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * use of "required" is discouraged - makes all future versions brittle!
       * </pre>
       *
       * <code>string data = 1;</code>
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        data_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object hexVersion_ = "";
      /**
       * <pre>
       *in proto3 field are optiona by default
       * </pre>
       *
       * <code>string hexVersion = 20;</code>
       */
      public java.lang.String getHexVersion() {
        java.lang.Object ref = hexVersion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hexVersion_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *in proto3 field are optiona by default
       * </pre>
       *
       * <code>string hexVersion = 20;</code>
       */
      public com.google.protobuf.ByteString
          getHexVersionBytes() {
        java.lang.Object ref = hexVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hexVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *in proto3 field are optiona by default
       * </pre>
       *
       * <code>string hexVersion = 20;</code>
       */
      public Builder setHexVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hexVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *in proto3 field are optiona by default
       * </pre>
       *
       * <code>string hexVersion = 20;</code>
       */
      public Builder clearHexVersion() {
        
        hexVersion_ = getDefaultInstance().getHexVersion();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *in proto3 field are optiona by default
       * </pre>
       *
       * <code>string hexVersion = 20;</code>
       */
      public Builder setHexVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        hexVersion_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:dataObject.DataClass)
    }

    // @@protoc_insertion_point(class_scope:dataObject.DataClass)
    private static final dataObject.DataClassProtoBufProxy.DataClass DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dataObject.DataClassProtoBufProxy.DataClass();
    }

    public static dataObject.DataClassProtoBufProxy.DataClass getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DataClass>
        PARSER = new com.google.protobuf.AbstractParser<DataClass>() {
      public DataClass parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new DataClass(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DataClass> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DataClass> getParserForType() {
      return PARSER;
    }

    public dataObject.DataClassProtoBufProxy.DataClass getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dataObject_DataClass_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dataObject_DataClass_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!DataClassProtoBufSerDeProxy.proto\022\ndat" +
      "aObject\"-\n\tDataClass\022\014\n\004data\030\001 \001(\t\022\022\n\nhe" +
      "xVersion\030\024 \001(\tB$\n\ndataObjectB\026DataClassP" +
      "rotoBufProxyb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_dataObject_DataClass_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dataObject_DataClass_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dataObject_DataClass_descriptor,
        new java.lang.String[] { "Data", "HexVersion", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
